# ----------------------------------------------------------------------
# Logging.
# ----------------------------------------------------------------------

logging:
    level.: WARN
    level.org.springframework: INFO
    level.fr.osb.deployapi: INFO


# ----------------------------------------------------------------------
# Repository manager.
# ----------------------------------------------------------------------

repositoryManager:
    api: http://artifactory.isiodata.fr/artifactory/api
    auth: "jenkins:jenkins"


# ----------------------------------------------------------------------
# Environments.
# ----------------------------------------------------------------------

env:
    # Remote deploy scripts file name format. The '{build}' part is dynamically replaced.
    scriptsFormat: deploy_{build}.sh

    integration:
        host: 192.168.51.9
        username: admin
        password: "******"
        scriptsFolder: /home/admin/deploy-scripts

    demo:
        host: 192.168.51.15
        username: admin
        password: "******"
        scriptsFolder: /home/admin/deploy-scripts